name: "ScanCode License Scanner"
description: "Simple ScanCode toolkit runner that scans for licenses and shows results"
author: "Your Name"
inputs:
  scan-path:
    description: "Path inside the target repo to scan"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install ScanCode Toolkit
      shell: bash
      run: |
        echo "Installing ScanCode Toolkit..."
        python -m pip install --upgrade pip
        pip install scancode-toolkit

    - name: Run ScanCode License Scan
      shell: bash
      run: |
        echo "Running ScanCode license scan on: ${{ inputs.scan-path }}"
        mkdir -p scancode-results
        scancode -l --json-pp scancode-results/results.json "${{ inputs.scan-path }}"

    - name: Display License Results
      shell: bash
      run: |
        echo "=== ScanCode License Scan Results ==="
        echo "Scanning completed successfully!"
        echo ""
        echo "Results saved to: scancode-results/results.json"
        
        if command -v jq >/dev/null 2>&1; then
          echo ""
          echo "License Summary:"
          LICENSES=$(jq -r '.files[]?.licenses[]?.spdx_license_key // empty' scancode-results/results.json 2>/dev/null | sort -u | grep -v '^$' || echo "")
          
          if [ -n "$LICENSES" ]; then
            echo "✅ Detected licenses:"
            echo "$LICENSES" | while read license; do
              echo "  - $license"
            done
          else
            echo "⚠️  No licenses detected in scan results"
          fi
        else
          ls -la scancode-results/results.json
        fi