name: "ORG ORT Full Scan"
description: "Runs full ORT scan workflow on a repository"
author: "Your Name"
runs:
  using: "python"
  main: "run_ort.py"
inputs:
  repo-path:
    description: "Path to the repository to scan"
    required: true
  ort-output:
    description: "Directory to save ORT results"
    required: false
    default: "ort-results"
  ort-analyzer:
    description: "Path to ORT CLI (if installed locally)"
    required: false
    default: "ort"
