name: "ScanCode License & Copyright Scan"
description: "Run ScanCode Toolkit to scan repository for licenses, copyrights, and dependencies"
author: "Your Name"

on:
  push:
  pull_request:

inputs:
  scan-path:
    description: "Path to scan"
    required: false
    default: "."
  output-name:
    description: "Artifact name / output directory"
    required: false
    default: "scancode-results"

jobs:
  scancode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install ScanCode Toolkit
        run: |
          python -m pip install --upgrade pip
          pip install scancode-toolkit==33.0.1

      - name: Run ScanCode Scan
        run: |
          mkdir -p "${{ inputs.output-name }}"
          scancode --license --copyright \
                   --json "${{ inputs.output-name }}/scancode.json" \
                   "${{ inputs.scan-path }}"

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.output-name }}
          path: ${{ inputs.output-name }}
