name: ORT
on:
  workflow_call:
    inputs:
      repo-path:
        required: true
        type: string
      ort-output:
        required: false
        type: string
        default: "ort-results"
      java-version:
        required: false
        type: string
        default: "11"

jobs:
  ort-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.repo-path }}
          
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          
      - name: Set up ORT
        run: |
          curl -Lo ort.zip https://github.com/oss-review-toolkit/ort/releases/download/68.2.0/ort-68.2.0.zip
          unzip ort.zip
          chmod +x ort/bin/ort
          echo "$PWD/ort/bin" >> $GITHUB_PATH
          
      - name: Run ORT Analyze
        run: |
          ort analyze -i ${{ inputs.repo-path }} -o ${{ inputs.ort-output }} --stacktrace
          
      - name: Generate ORT Report
        run: |
          ort report -i ${{ inputs.ort-output }}/analyzer-result.yml -o ${{ inputs.ort-output }}/report --report-formats Html,PlainTextTemplate
          
      - name: Upload ORT Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.ort-output }}
          path: ${{ inputs.ort-output }}