name: "ScanCode License & Copyright Scan"
description: "Run ScanCode Toolkit to scan repository for licenses, copyrights, and dependencies"
author: "Your Name"
runs:
  using: "composite"
  inputs:
    scan-path:
      description: "Path to scan"
      required: true
      default: "."
    output-name:
      description: "Artifact name / output directory"
      required: true
      default: "scancode-results"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install ScanCode Toolkit
      run: |
        python -m pip install --upgrade pip
        pip install scancode-toolkit

    - name: Run ScanCode Scan
      run: |
        mkdir -p ${{ inputs.output-name }}
        scancode --license --copyright --json ${{ inputs.output-name }}/scancode.json ${{ inputs.scan-path }}
      shell: bash

    - name: Upload Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output-name }}
        path: ${{ inputs.output-name }}
